### PR TITLE
Updated link to indent specification in readme

### PR DESCRIPTION
**Pull request by KevinGreene**
Before submitting a PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [X] The commits are consistent with our [contribution guidelines](../CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s). Indentation & font-lock tests are extremely important!
- [ ] All tests are passing (`make test`)
- [ ] The new code is not generating bytecode or `M-x checkdoc` warnings
- [ ] You've updated the changelog (if adding/changing user-visible functionality)
- [X] You've updated the readme (if adding/changing user-visible functionality)

Thanks!

### CODE REVIEW

**Comment by bbatsov** [comment]
Can you please change `Updated` to `Update` in your commit message?

**Comment by Malabarba** [comment]
That URL 404s for me.

**Comment by Malabarba** [comment]
Besides, we should probably point to the new manual. :-)

**Comment by bbatsov** [comment]
The link works for me, but yeah - probably it'd best to link to cider.readthedocs.org.

**Comment by KevinGreene** [comment]
I've fixed the commit message (removed `d`) and now point to http://cider.readthedocs.org/en/latest/indent_spec/

**Comment by bbatsov** [comment]
👍 Thanks!

**Pull request merged**
