### PR TITLE
Add default keybindings for rename-ns-alias and add-arity refactorings, and refactor clojure-unwind

### PR DESCRIPTION
**Pull request by yuhan0**
I placed these suggested bindings under the clojure-refactor-map and added them to the menubar:
`C-c C-r n r` -> `clojure-rename-ns-alias`
`C-c C-r a` -> `clojure-add-arity`

The `a` keybinding was taken by `clojure-unwind-all` which didn't made much sense, so I took the liberty of changing it to `U` as a "stronger" version of the existing `u -> clojure-unwind` binding.

-----------------

Before submitting a PR mark the checkboxes for the items you've done (if you
think a checkbox does not apply, then leave it unchecked):

- [x] The commits are consistent with our [contribution guidelines][1].
- [ ] You've added tests (if possible) to cover your change(s). Bugfix, indentation, and font-lock tests are extremely important!
- [x] You've run `M-x checkdoc` and fixed any warnings in the code you've written.
- [x] You've updated the changelog (if adding/changing user-visible functionality).
- [ ] You've updated the readme (if adding/changing user-visible functionality).

### CODE REVIEW

**Comment by bbatsov** [comment]
> The a keybinding was taken by clojure-unwind-all which didn't made much sense, so I took the liberty of changing it to U as a "stronger" version of the existing u -> clojure-unwind binding.

Uppercase bindings are both hard to press and a bit confusing for the end users, so I generally avoid them. Probably in this case we can fold a few of the `*-all` commands into the parent commands and make the invokable with a prefix arg.

**Comment by yuhan0** [comment]
Would you like that to be done in this PR? It sounds like quite a big breaking change and personally I prefer having separate commands for discoverability instead of using prefix args. 

Another option in this case could be `u w -> unwind` and `u a -> unwind-all`, or `u` for one and `C-u` for the other, although that would somewhat break symmetry with the rest of the bindings.

**Comment by bbatsov** [comment]
> Would you like that to be done in this PR? It sounds like quite a big breaking change and personally I prefer having separate commands for discoverability instead of using prefix args.

That makes sense under a certain point - when you start running out of meaningful keybindings you know you have to start compacting things and group them together. I'm not saying to remove the existing command - I'm just saying to remove its dedicated keybinding. I think such commands are a classic use case for a prefix key as technically this is just an extension of the core behaviour. 

Changing the existing key is just as big of a breaking change as far as I'm concerned, so nothing really changes in the end. 

> Another option in this case could be u w -> unwind and u a -> unwind-all, or u for one and C-u for the other, although that would somewhat break symmetry with the rest of the bindings.

Extra prefixes should be utilized only to group multiple related commands. E.g. - if we had more commands that operated on function definitions it would make sense to put them under some shared prefix.

**Comment by yuhan0** [comment]
Ok, I refactored `clojure-unwind` to take a numeric prefix / universal argument, and removed the dedicated key binding for `clojure-unwind-all`

**Comment by bbatsov** [comment]
The changes look great! Don't forget to update the changelog as well.

**Comment by yuhan0** [comment]
Done, and added a couple of tests as well :)

**Comment by bbatsov** [comment]
Lovely! Thank you! 🙇

**Pull request merged**
