### PR TITLE
Fix doctring indentation issue in #241

### PR DESCRIPTION
**Pull request by sandhu**
Added code to only apply the prefix if the current indent level is <=
the default prefix spacing.

### CODE REVIEW

**Comment by bbatsov** [comment]
We need to implement some indentation tests first. See my comments here https://github.com/clojure-emacs/clojure-mode/pull/283

I you get the ball rolling on the tests, I'll gladly accept the patch. As it stands, with no indentation tests every change is a potential problem and I'd rather avoid those.

**Comment by sandhu** [comment]
Fair point. I'll look into creating the tests.

**Comment by bbatsov** [comment]
@sandhu Ping :-)

**Comment by bbatsov** [comment]
Btw, I just added some basic indentation tests to get you started.

**Comment by expez** [comment]
@sandhu Did you get around to looking at the tests for this fix?

**Comment by sandhu** [comment]
Sorry. Seem to have missed the ping from @bbatsov as well.

Will take a look at them this weekend and update the PR.

**Comment by sandhu** [comment]
Added the doc string indentation tests

**Comment by expez** [comment]
Cool.  Could you squash the commits?

**Comment by sandhu** [comment]
Done.

**Comment by expez** [comment]
There's still an empty merge commit.

**Comment by sandhu** [comment]
I've removed the merge commit.

**Comment by sandhu** [comment]
I've added the merge commit back in since it shows conflicts without it there.

**Comment by expez** [comment]
We don't want merge commits polluting our history.  In the contribution guidelines there's [this link](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) about how to rebase to avoid creating merge commits.

`git rebase` is a very powerful tool so even if this is pissing you off, your future self will benefit from having learned about it :)

**Comment by bbatsov** [comment]
You should rebase on top of the current master.

On Saturday, June 13, 2015, Achint Sandhu <notifications@github.com> wrote:

> I've added the merge commit back in since it shows conflicts without it
> there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/clojure-mode/pull/289#issuecomment-111738416>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by sandhu** [comment]
I don't generally rebase since it's not an accurate reflection of the history, but since it's your repo, I'm happy to play along. :-)

Just pushed a rebased version.

**Comment by bbatsov** [comment]
Thanks!

**Comment by sandhu** [comment]
No worries. Thanks for the merge.

**Pull request merged**
