### PR TITLE
Treat , as a non-logical sexpr character

### LINKED ISSUE #367: Vertical alignment doesn't treat , correctly
```clojure
(def ^:private start-element
  {:meta "^", :meta* "#^", :vector "[",       :map "{"
   :list "(", :eval "#=",  :uneval "#_",      :fn "#("
   :set "#{", :deref "@",  :reader-macro "#", :unquote "~"
   :var "#'", :quote "'",  :syntax-quote "`", :unquote-splicing "~@"})
```

indents with align-vertically to 

```clojure
(def ^:private start-element
  {:meta "^"  , :meta* "#^" , :vector        "["  ,       :map        "{"
   :list "("  , :eval  "#=" ,  :uneval       "#_" ,      :fn          "#("
   :set  "#{" , :deref "@"  ,  :reader-macro "#"  , :unquote          "~"
   :var  "#'" , :quote "'"  ,  :syntax-quote "`"  , :unquote-splicing "~@"})
```

since `,` is lexical whitespace, the `,`s should remain attached to the preceding forms.

### PR DESCRIPTION
**Pull request by arrdem**
This causes clojure-forward-logical-sexp to skip over , when for
instance computing vertical alignments.

Fixes #367

### CODE REVIEW

**Comment by Malabarba** [comment]
Well, I guess that was easier than expected. :smile: 
Could also add a test for this in the alignment tests? It's very easy to write. Just copy one of the other tests in there, and replace the code string with an example that failed before but works now.

**Comment by Malabarba** [comment]
And thanks a ton btw!

**Comment by arrdem** [comment]
Yeah I'm honestly kinda surprised that this is all it took even in some fairly torturous case...

2016-03-25-204426_251x86_scrot

**Comment by arrdem** [comment]
I don't think this is right however 
2016-03-25-204523_311x87_scrot

**Comment by arrdem** [comment]
This is also pretty tortured....

2016-03-25-204641_213x114_scrot

**Comment by arrdem** [comment]
Also isn't right... not sure what's going on here.

2016-03-25-205058_615x105_scrot

**Comment by Malabarba** [comment]
Hmm. Now that I think about it... The current code probably assumes that non-logical sexps come *before* the logical sexp, which is not true for commas. 
I don't think we need to change that, though (commas aren't really sexps anyway). It should be enough to just `(skip-chars-forward ",")` after moving over a *logical* sexp. This won't cover some of the more tortuous cases you tried above, but it should cover the case of a single comma after a sexp, which is really the only one I'm concerned with.

**Comment by arrdem** [comment]
Okay. These two together seem to do the job better.
2016-03-26-232339_241x65_scrot

**Comment by Malabarba** [comment]
Merged! I also added a bit of code so that `clojure-align` will automatically cleanup excessive commas.

**Comment by arrdem** [comment]
Did you test this at all for yourself? I'm concerned that it has fairly significant limitations from mucking this afternoon :disappointed:

**Comment by Malabarba** [comment]
I did, but I also changed the code a bit, which might have overcome the limitations. Have you tried the version on master?

**Comment by arrdem** [comment]
No I've been in hospital all day. I'll check it out tomorrow.

**Comment by Malabarba** [comment]
:+1: Let me know.

**Comment by arrdem** [comment]
LGTM. Thanks Artur!

2016-03-28-102731_583x97_scrot

**Pull request merged**
