### PR TITLE
Many indentation improvements

### PR DESCRIPTION
**Pull request by Malabarba**

### CODE REVIEW

**Comment by bbatsov** [comment]
Nice PR! Just add some tests here https://github.com/clojure-emacs/clojure-mode/blob/master/test/clojure-mode-indentation-test.el for every commit.

**Comment by Malabarba** [comment]
All pushed, let's see if it passes.

**Comment by Malabarba** [comment]
I'm not sure what's the matter here. The test is pretty simple and it passes for me locally.

**Comment by bbatsov** [comment]
Might be something to do with the Emacs version. The tests are running on 24.3 and I doubt you're using it yourself. The failing test itself looks simple enough, so I'm guessing the problem is in the indentation logic.

**Comment by Malabarba** [comment]
Except it's failing on the snapshot build too. Or is that a mislabeled build?

**Comment by bbatsov** [comment]
Ancient snapshot - this repo hasn't been updated in years...

**Comment by bbatsov** [comment]
See https://launchpad.net/~cassou/+archive/ubuntu/emacs

**Comment by Malabarba** [comment]
I see...
Hopefully I can reproduce it in 24.5. For some reason 24.3 is the only version I never managed to install with evm.

**Comment by Malabarba** [comment]
OK, it was `cl`'s fault. It's passing now.

**Pull request merged**
