### PR TITLE
Font-lock `code` marks, just like `elisp-quotes'

### PR DESCRIPTION
**Pull request by Malabarba**

### CODE REVIEW

**Comment by bbatsov** [comment]
I've been thinking of adding this, but I'm not sure this simple solution is robust enough. Shouldn't we actually do some additional processing of docstrings? I believe this is how it's implemented in `lisp-mode` and friends.

**Comment by Malabarba** [comment]
I dunno, but the version here works fine in docstrings and comments. I'll try to see how it's done in elisp.

**Comment by bbatsov** [comment]
Guess I had too much faith in `lisp-mode`. I checked their solution and it's actually not considering the context at all - meaning `fdfdf' is font-locked the same regardless of where it appears (even at the top-level). If I knew this I would have added such font-locking eons ago.  :-)

**Comment by Malabarba** [comment]
:smile:

**Pull request merged**
