### PR TITLE
 Associate boot profile scripts with clojure-mode

### PR DESCRIPTION
**Pull request by aJchemist**
Both build.boot and profile.boot are clojure source files.

### CODE REVIEW

**Comment by bbatsov** [comment]
Please update your commit message to match our contribution conventions (e.g. https://github.com/clojure-emacs/clojure-mode/commit/e2176346e1e6760a2121507a1085ec6645cf65d4)

**Comment by bbatsov** [comment]
@aJchemist ping (commit amend, force push)

**Comment by aJchemist** [comment]
@bbatsov pong (oh sorry, I'm late)

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
