### PR TITLE
Indent clojure.spec/fdef differently

### PR DESCRIPTION
**Pull request by ghadishayban**
```clj
;; before
(s/fdef ::uhhuh
        :args (s/keys :req [::hello])
        :ret any?)
;; after
(s/fdef ::uhhuh
  :args (s/keys :req [::hello])
  :ret any?)
```

**Replace this placeholder text with a summary of the changes in your PR.**

-----------------

Before submitting a PR mark the checkboxes for the items you've done (if you
think a checkbox does not apply, then leave it unchecked):

- [ ] The commits are consistent with our [contribution guidelines][1].
- [ ] You've added tests (if possible) to cover your change(s). Bugfix, indentation, and font-lock tests are extremely important!
- [ ] You've run `M-x checkdoc` and fixed any warnings in the code you've written.
- [ ] You've updated the changelog (if adding/changing user-visible functionality).
- [ ] You've updated the readme (if adding/changing user-visible functionality).

Thanks!

[1]: https://github.com/clojure-emacs/clojure-mode/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by ghadishayban** [comment]
CI appeared to fail for reasons I think unrelated to this change

**Comment by bbatsov** [comment]
I'm fine with the change, just mention it in the changelog please.

**Comment by ghadishayban** [comment]
Thanks @bbatsov. I've done that now.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
